Part 5: Lifecycle Hooks and Reactivation
sajeezy/root-product-builder-fundamentals pull request #6
Opened 2023-12-08 07:11 UTC by sajeezy

### Which part of the onboarding is this for?

- [ ] Part 1: Getting Set Up with Your First Product
- [ ] Part 2: Generating Insurance Quotes
- [ ] Part 3: Issuing Policies
- [ ] Part 4: Part 4: Amending Policies with Alteration Hooks
- [x] Part 5: Lifecycle Hooks and Reactivation
- [ ] Part 6: Scheduled Functions and Anniversary Logic
- [ ] Part 7: Crafting Documents and Documentation
- [ ] Part 8: Building a Claims and Payout Flow

### What has been implemented in this PR?
Root Product Builder Fundamentals Course Part 5: Lifecycle Hooks and Reactivation

### How was testing done?

**Types of tests required**

- [x] Unit test check (tests to be done prior to handing to reviewer)
- [x] API endpoint testing

**Acceptance criteria**
- [ ] If a policy is in a lapsed or cancelled state, it can be reactivated via the Root API or Dashboard.
- [ ] The policy has a reactivation date added to the module data on reactivation. 
- [x] Unit tests are written to see that a policy can be reactivated and the correct data is added to it. 

- Unit tests for Reactivation flow
  - A policy being reactivated with a status of cancelled and lapsed can be reactivated. 
  - A policy with a status of expired cannot be reactivated.
 
**Link to a working quote, application, policy or claim - whichever is relevant to the part**
Screenshot of Unit tests
![CleanShot 2023-12-08 at 09 04 37](https://github.com/sajeezy/root-product-builder-fundamentals/assets/3699393/02fcab72-abfd-482a-8ac4-1dbde64c7920)

### Authors considerations checklist

- [ ] Has unit tests been written to prove the PR is working?
- [ ] Is this PR being created into the correct branch (main or development)?

### Feedback and review

#### Were the specifications and Root guides clear enough?
- The guides gave me a great understanding of what to do considering there wasn't alot of data provided in the Onboarding doc so the guides came in handy.

#### What could have been explicated better to make this part easier to understand?
- I used the API mostly for this section. Its not clear to me why policy actions on the dashboard are disabled. I thought (maybe still think), I needed to create an alteration for Reactivate but I saw 'Reactivate' action already so I'm confused about that. 

### Part Specific Questions
What other limits do you think would be useful to add to policy reactivation restrictions?
- Some business rules like reactivation can only happen in a 3 month or 6 month window
- A request for approval ie the reactivation rules can be defined by one user but they are not set by that same user. It could have some sort of account / audit controls to another person to approve.

2023-12-11 12:50 UTC, theunisduminy commented on code/08-lifecycle-hooks.js
> +  }
Hey @sajeezy, why was this logic added to the feature? It's not part of the specification.

2023-12-11 12:51 UTC, theunisduminy commented on code/08-lifecycle-hooks.js
> +    reactivation_date: '2024-03-01', //policy.start_date,
Should be the day policy was activated so:
`reactivation_date: moment()`

2023-12-11 12:57 UTC, sajeezy commented on code/08-lifecycle-hooks.js
> +    reactivation_date: '2024-03-01', //policy.start_date,
Got you. Cool will make that change

2023-12-11 12:58 UTC, sajeezy commented on code/08-lifecycle-hooks.js
> +  }
Agreed. Will resolve thanks

2023-12-12 06:35 UTC, theunisduminy commented on code/08-lifecycle-hooks.js
> +    }),
Not necessary to have both, one option should suffice here! 😄 

We sometimes use two hooks if they have different logic associated with them, so you're able to write separate logic using lifecycle hooks.

2023-12-12 06:36 UTC, theunisduminy requested changes
One minor comment then we're good to go!

2023-12-12 08:19 UTC, theunisduminy approved these changes
Thanks @sajeezy 😄

2023-12-12 08:19 UTC, merged